apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  type: LoadBalancer    # This tells your Mac to give it a localhost port
  selector:
    app: chatbot        # This MUST match the label in your deployment.yaml
  ports:
    - protocol: TCP
      port: 80          # Port the service listens on
      targetPort: 8501  # Port your Streamlit app is actually running on